# Generated by Django 2.2.12 on 2020-07-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('typeV', models.CharField(choices=[('Nature', 'Nature'), ('Architecture', 'Architecture'), ('Plages', 'Plages'), ('Aventure', 'Aventure'), ('désert', 'désert')], default='Plages', max_length=2)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=None)),
            ],
        ),
    ]
